name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2

      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: install modules
        run: npm install

      - name: run build
        run: npm run build

      - name: run unit tests
        run: npm run test:unit

      - name: run e2e tests
        run: npm run test:e2e

      - name: lint code
        run: npm run lint

      - name: run storybook
        run: npm run build:storybook

      - name: run typeckeck
        run: npm run type:check

      - name: language translation check
        run: i18n:check
